# Generated by Django 4.1.6 on 2023-02-07 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sacco1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='National_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
    ]
