# Generated by Django 4.1.7 on 2023-02-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco1', '0002_members_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='Status',
        ),
    ]
