# Generated by Django 4.1.7 on 2023-02-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco1', '0005_rename_next_of_kin_members_next_of_kin_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='movie_image',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
    ]
