# Generated by Django 4.1.7 on 2023-02-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sacco1', '0006_members_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='movie_image',
            new_name='m_image',
        ),
    ]
