# Generated by Django 4.1.7 on 2023-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco1', '0008_alter_expenses_options_alter_loan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='Ammount_saved',
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
